# Generated by Django 5.2.8 on 2025-11-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_remove_movieinfo_image_movieinfo_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movieinfo',
            table='movie_info',
        ),
    ]
